### PR TITLE
A couple blocks.

### PR DESCRIPTION
**Pull request by ThatRedox**
- Azelea
- Bed
- Bell
- BigDripleaf
- BigDripleafStem
- Button
- Cactus

image
image

### CODE REVIEW

**Comment by ThatRedox** [comment]
- Cake
- Cake With Candle
- Candle
- Carpet
- Chain
- Chest
- Chorus Flower
- Coca Plant
image

**Comment by ThatRedox** [comment]
- Comparator
- Crops
- Daylight Sensor
- Door
- Dragon Egg
- Enchantment Table
- End Portal Frame
- End Portal
- End Rod
image
image

**Comment by ThatRedox** [comment]
- Fence Gate
- Fence
- Glow Lichen
- Grass Path
- Grindstone
- Iron Bars
- Ladder
- Lantern
image
image

**Comment by ThatRedox** [comment]
- Chorus Plant
- Composter
- Jigsaw
image

**Comment by ThatRedox** [comment]
image

**Comment by ThatRedox** [comment]
image
image

**Comment by ThatRedox** [comment]
image

**Comment by ThatRedox** [comment]
image

**Comment by ThatRedox** [comment]
image

**Comment by ThatRedox** [comment]
Debug-16

**Comment by ThatRedox** [comment]
image
image

**Comment by ThatRedox** [comment]
image
image

**Comment by ThatRedox** [comment]
Debug-64

**Comment by leMaik** [comment]
That escalated quickly! :rocket: Thank you so much for this, I know this stuff is a chore…

**Comment by leMaik** [comment]
Reminder for mushrooms

**Pull request merged**
